server:
  port: 8080
spring:
  application:
    name: spring-rest-security
  profiles:
    active: dafault
  datasource:
    url: jdbc:postgresql://localhost:5432/kateryna_db
    username: postgres
    password: helloworld
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    data: classpath:data.sql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: false
security:
  jwt:
    secret-key: katerynakey